# Generated by Django 4.0.3 on 2022-03-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlater',
            name='image',
            field=models.URLField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='watchlater',
            name='title',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
