# Generated by Django 4.0.3 on 2022-03-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_dislikes_review_likes_delete_reviewlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(),
        ),
    ]
